name: WorldGuardExtraFlagsPlus
description: Adds more flags to WorldGuard to help manage your server easily!

version: 4.2.5-SNAPSHOT
api-version: 1.20

author: isokissa3
website: https://joniaromaa.fi

depend: [ WorldGuard ]
softdepend: [ ProtocolLib ]

main: dev.tins.worldguardextraflagsplus.WorldGuardExtraFlagsPlusPlugin


