name: WorldGuardExtraFlagsPlus
description: |
  Adds more flags to WorldGuard to help manage your server easily!
  GitHub: https://github.com/tins-dev/WorldGuardExtraFlagsPlus
  Documentation: -- tins --
  Original author Website: https://joniaromaa.fi
main: dev.tins.worldguardextraflagsplus.WorldGuardExtraFlagsPlusPlugin
version: 4.3.0
api-version: 1.20
depend: [ WorldGuard ]
softdepend: [ ProtocolLib ]

authors: [tins, isokissa3]

