name: Build And Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: WorldGuardExtraFlagsPlus Jar
      uses: actions/upload-artifact@v2
      with:
        name: WorldGuardExtraFlagsPlus Jar
        path: "${{ github.workspace }}/Spigot/target/WorldGuardExtraFlagsPlus.jar"



