name: Build And Deploy

on:
  push:
    branches: [ master ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: WorldGuardExtraFlagsPlus Jar
      uses: actions/upload-artifact@v2
      with:
        name: WorldGuardExtraFlagsPlus Jar
        path: "${{ github.workspace }}/Spigot/target/WorldGuardExtraFlagsPlus.jar"
  
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: Spigot/target/WorldGuardExtraFlagsPlus.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



